### ISSUE TITLE
Cannot set property 'DialogsManager' of undefined

### ISSUE THREAD

**Issue by alpipego** [kobizz/dialogs-manager#9]
A colleague noticed this issue in Elementor (it seems that more people are having this issue https://github.com/elementor/elementor/issues/12283). 

It gets checked if `module` is not undefined, but not if `module.exports` isn't:

https://github.com/kobizz/dialogs-manager/blob/master/src/js/dialogs-manager.js#L1003 

Line 1003 should probably be `(typeof module !== 'undefined' && typeof module.exports !== 'undefined') ? module.exports : window`

**Comment by kobizz** [comment]
Thank you, @alpipego.

Although this issue doesn't seem to be related to the Elementor's issue you referenced, it's indeed should be fixed.
